apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cas.fullname" . }}-config
  labels:
    {{- include "cas.labels" . | nindent 4 }}
data:
  CAS_PROPERTIES: |
    {
      "cas": {
        "ticket": {
          "registry": {
            {{- if .Values.hazelcast.enabled }}
            "hazelcast": {
              "cluster": {
                "core": {
                  "instance-name": "{{ .Values.hazelcast.cluster.instanceName }}",
                  "backup-count": {{ .Values.hazelcast.cluster.backupCount }},
                  "async-backup-count": {{ .Values.hazelcast.cluster.asyncBackupCount }},
                  "eviction-policy": "{{ .Values.hazelcast.cluster.evictionPolicy }}",
                  "max-size-policy": "{{ .Values.hazelcast.cluster.maxSizePolicy }}",
                  "max-size": {{ .Values.hazelcast.cluster.maxSize }},
                  "enable-jet": {{ .Values.hazelcast.cluster.enableJet }}
                },
                "network": {
                  "tcpip-enabled": {{ .Values.hazelcast.tcpIpEnabled }},
                  "port": {{ .Values.hazelcast.port }},
                  "members": [{{ .Values.hazelcast.members }}]
                }
              }
            }
            {{- end }}
            {{- if and .Values.hazelcast.enabled .Values.redis.enabled }},{{ end }}
            {{- if .Values.redis.enabled }}
            "redis": {
              "sentinel": {
                "master": "{{ .Values.redis.sentinel.master }}",
                "node": ["{{ .Values.redis.sentinel.hosts }}"]
              },
              "database": {{ .Values.redis.database }},
              "timeout": "{{ .Values.redis.timeout }}",
              "connect-timeout": "{{ .Values.redis.connectTimeout }}",
              "pool": {
                "enabled": true,
                "max-active": {{ .Values.redis.pool.maxActive }},
                "max-idle": {{ .Values.redis.pool.maxIdle }},
                "min-idle": {{ .Values.redis.pool.minIdle }}
              }
            }
            {{- end }}
          }
        },
        "monitor": {
          "endpoints": {
            "endpoint": {
              "defaults": {
                "access": "PERMIT"
              },
              "health": {
                "access": "PERMIT",
                "group": {
                  "cluster": {
                    "include": "clusterHealthIndicator"
                  }
                }
              }
            }
          }
        }
      },
      "management": {
        "endpoint": {
          "health": {
            "show-details": "always",
            "group": {
              "cluster": {
                "include": "clusterHealthIndicator"
              }
            }
          }
        },
        "endpoints": {
          "web": {
            "exposure": {
              "include": "health,info,prometheus,cluster"
            }
          }
        }
      }
    }
