apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cas.fullname" . }}
  labels:
    app: {{ include "cas.fullname" . }}
spec:
  serviceName: {{ include "cas.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cas.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "cas.fullname" . }}
    spec:
      containers:
        - name: cas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: hazelcast
              containerPort: 5701
              protocol: TCP
          env:
            # Hazelcast TCP Discovery
            - name: CAS_TICKET_REGISTRY_HAZELCAST_CLUSTER_NETWORK_TCPIP_ENABLED
              value: "true"
            - name: CAS_TICKET_REGISTRY_HAZELCAST_CLUSTER_NETWORK_TCPIP_MEMBERS
              value: {{ .Values.hazelcast.members | quote }}
            - name: CAS_TICKET_REGISTRY_HAZELCAST_CLUSTER_MULTICAST_ENABLED
              value: "false"
            
            # Redis Sentinel Configuration
            - name: CAS_TICKET_REGISTRY_REDIS_SENTINEL_MASTER
              value: {{ .Values.redis.sentinel.master | quote }}
            - name: CAS_TICKET_REGISTRY_REDIS_SENTINEL_NODE_0
              value: {{ index (splitList "," .Values.redis.sentinel.nodes) 0 | quote }}
            - name: CAS_TICKET_REGISTRY_REDIS_SENTINEL_NODE_1
              value: {{ index (splitList "," .Values.redis.sentinel.nodes) 1 | quote }}
            - name: CAS_TICKET_REGISTRY_REDIS_SENTINEL_NODE_2
              value: {{ index (splitList "," .Values.redis.sentinel.nodes) 2 | quote }}
          livenessProbe:
            httpGet:
              path: /cas/actuator/health/cluster
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /cas/actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
